# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

CRATES="
	aws-lc-rs@1.17.0
	aws-lc-sys@0.41.0
	base64@0.22.1
	bytes@1.11.1
	cc@1.2.62
	cfg-if@1.0.4
	cmake@0.1.58
	dunce@1.0.5
	dyn-clone@1.0.20
	find-msvc-tools@0.1.9
	fs_extra@1.3.0
	getrandom@0.2.17
	getrandom@0.3.4
	http@1.4.0
	httparse@1.10.1
	itoa@1.0.18
	jiff-static@0.2.24
	jiff@0.2.24
	jobserver@0.1.34
	libc@0.2.186
	libmimalloc-sys@0.1.47
	log@0.4.29
	memchr@2.8.0
	mimalloc@0.1.50
	minreq@3.0.0-rc.1
	once_cell@1.21.4
	percent-encoding@2.3.2
	pkg-config@0.3.33
	portable-atomic-util@0.2.7
	portable-atomic@1.13.1
	proc-macro2@1.0.106
	quote@1.0.45
	r-efi@5.3.0
	ring@0.17.14
	rustls-pki-types@1.14.1
	rustls-webpki@0.103.13
	rustls@0.23.40
	schemars@0.8.22
	schemars_derive@0.8.22
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_derive_internals@0.29.1
	serde_json@1.0.149
	shlex@1.3.0
	sqlite3-src@0.7.0
	sqlite3-sys@0.18.0
	sqlite@0.37.0
	subtle@2.6.1
	syn@2.0.117
	unicode-ident@1.0.24
	untrusted@0.9.0
	ureq-proto@0.6.0
	ureq@3.3.0
	utf8-zero@0.8.1
	wasi@0.11.1+wasi-snapshot-preview1
	wasip2@1.0.3+wasi-0.2.9
	webpki-roots@1.0.7
	windows-link@0.2.1
	windows-sys@0.52.0
	windows-sys@0.61.2
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	wit-bindgen@0.57.1
	zeroize@1.8.2
	zmij@1.0.21
"

inherit cargo
DESCRIPTION="Usage analysis tool for Claude Code token usage and costs"
HOMEPAGE="https://github.com/ryoppippi/ccusage https://ccusage.com/"
SRC_URI="
	https://github.com/ryoppippi/ccusage/archive/refs/tags/v${PV}.tar.gz
	${CARGO_CRATE_URIS}
"

S="${WORKDIR}/${P}/rust/crates/ccusage"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD CDLA-Permissive-2.0 ISC MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"
